worker_processes  5;  ## Default: 1

events {
  worker_connections  4096;  ## Default: 1024
}

http{
	server {
		listen 80;
		server_name microservices.com;
		client_max_body_size 500M;
		location / {
			root /usr/share/nginx/html;
			index index.html;
		}

		## Two default routes

		location / {
				proxy_pass http://frontend:3000/;
				proxy_http_version 1.1;
				proxy_set_header Origin $http_origin;
				proxy_set_header Upgrade $http_upgrade;
				proxy_set_header Connection 'upgrade';
				proxy_set_header Host $host;
				proxy_set_header X-Real-IP $remote_addr;
				proxy_cache_bypass $http_upgrade;

				## For CORS
				proxy_set_header Access-Control-Allow-Origin $http_origin;
				proxy_set_header Access-Control-Allow-Methods $http_access_control_request_method;
				proxy_set_header Access-Control-Allow-Headers $http_access_control_request_headers;
		}

		location /api/ {
				proxy_pass http://backend:5000/;
				proxy_http_version 1.1;
				proxy_set_header Origin $http_origin;
				proxy_set_header Upgrade $http_upgrade;
				proxy_set_header Connection 'upgrade';
				proxy_set_header Host $host;
				proxy_set_header X-Real-IP $remote_addr;
				proxy_cache_bypass $http_upgrade;

				## For CORS
				proxy_set_header Access-Control-Allow-Origin $http_origin;
				proxy_set_header Access-Control-Allow-Methods $http_access_control_request_method;
				proxy_set_header Access-Control-Allow-Headers $http_access_control_request_headers;
		}

		location /frontend/ {
				proxy_pass http://frontend:3000/;
				proxy_http_version 1.1;
				proxy_set_header Origin $http_origin;
				proxy_set_header Upgrade $http_upgrade;
				proxy_set_header Connection 'upgrade';
				proxy_set_header Host $host;
				proxy_set_header X-Real-IP $remote_addr;
				proxy_cache_bypass $http_upgrade;

				## For CORS
				proxy_set_header Access-Control-Allow-Origin $http_origin;
				proxy_set_header Access-Control-Allow-Methods $http_access_control_request_method;
				proxy_set_header Access-Control-Allow-Headers $http_access_control_request_headers;
		}



		
	}
}